config/routes.rb
Rails.application.routes.draw do

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'

  get '/signup', to: 'users#new'
  post '/users', to: 'users#create'
  resources :users

  get 'welcome' => 'pages#home'
  get '/movies', to: 'movies#index', as: :movies
  get '/movies/:id', to: 'movies#show', as: :movie
  resources :movies do
      resources :movie_quotes
  end

  get '/actors', to: 'actors#index', as: :actors
  get '/actors/:id', to: 'actors#show', as: :actor

end

app/models/actor.rb
class Actor < ActiveRecord::Base
  has_many :parts
  has_many :movies, through: :parts

  attr_accessor :role

end

app/models/concerns/actor_role.rb
module ActorRole

  def loaded
    roles.each do |role|
      proxy_association.target << role
    end
  end

  private

  def roles
    return_array = []
        through_collection.each_with_index do |through,i|
            associate = through.send(reflection_name)
            associate.assign_attributes({role: items[i]}) if items[i].present?
            return_array.concat Array.new(1).fill( associate )
        end
        return_array
    end

    #######################
    #      Variables      #
    #######################

    #Association
    def reflection_name
        proxy_association.source_reflection.name
    end

    #Foreign Key
    def through_source_key
        proxy_association.reflection.source_reflection.foreign_key
    end

    #Primary Key
    def through_primary_key
        proxy_association.reflection.through_reflection.active_record_primary_key
    end

    #Through Name
    def through_name
        proxy_association.reflection.through_reflection.name
    end

    #Through
    def through_collection
        proxy_association.owner.send through_name
    end

    #Captions
    def items
        through_collection.map(&:role)
    end

    #Target
    def target_collection
        #load_target
        proxy_association.target
    end

end

app/models/movie.rb
class Movie < ActiveRecord::Base
  has_many :parts
  has_many :actors, through: :parts, extend: ActorRole
  has_many :movie_quotes


end

app/models/movie_quote.rb
class MovieQuote < ActiveRecord::Base
  belongs_to :movie
end

app/models/part.rb
class Part < ActiveRecord::Base
  belongs_to :movie
  belongs_to :actor
end

app/models/user.rb
class User < ActiveRecord::Base

  has_secure_password

end

app/controllers/actors_controller.rb
class ActorsController < ApplicationController
  before_action :set_actor, only: [:show, :edit, :update, :destroy]

  def index
    @actors = Actor.all
  end

  def show
    @movies = @actor.movies
  end




  private

  def set_actor
    @actor = Actor.find(params[:id])
  end

  # function used on create and update to verify params are correct
  def actor_params
    params.require(:actor).permit(:first_name,:last_name,:bio)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def current_user
   @current_user ||= User.find(session[:user_id]) if session[:user_id]
 end
 helper_method :current_user

 def authorize
   redirect_to '/login' unless current_user
 end
 
end

app/controllers/movie_quotes_controller.rb
class MovieQuotesController < ApplicationController

  before_filter :authorize

  def create
    @movie = Movie.find(params[:movie_id])
    @movie_quote = @movie.movie_quotes.create(movie_quote_params)
    redirect_to movie_path(@movie)
  end

  private

  def movie_quote_params
    params.require(:movie_quote).permit(:source, :quote)
  end

end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  before_action :set_movie, only: [:show, :edit, :update, :destroy]

  def index
    @movies = Movie.all
  end

  def show
    @actors = @movie.actors
  end

  private

  def set_movie
    @movie = Movie.find(params[:id])
  end

  def movie_params
    params.require(:movie).permit(:title, :release_year, :plot)
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

	def home

	end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def create
    user = User.find_by_email(params[:email])
    # If the user exists AND the password entered is correct.
    if user && user.authenticate(params[:password])
      # Save the user id inside the browser cookie. This is how we keep the user
      # logged in when they navigate around our website.
      session[:user_id] = user.id
      redirect_to '/'
    else
      # If user's login doesn't work, send them back to the login form.
      redirect_to '/login'
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to '/login'
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to '/'
    else
      redirect_to '/signup'
    end
  end

  private

  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :password)
  end

end

app/helpers/actors_helper.rb
module ActorsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

  def title(page_title)
    content_for :title, page_title.to_s
  end

end

app/helpers/movie_quotes_helper.rb
module MovieQuotesHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/actors/index.html.erb
<div class="jumbotron">
  <h1>ACTOR</h1>
  <p class="lead">ac·tor  (ăk′tər)</p>
  <p><%= link_to 'Movies', movies_path(), class:"btn btn-lg btn-success"%></p>
</div>

<div class="row ">
  <% @actors.each do |a| %>
  <div class="col-md-6">
    <h4><%= a.first_name %><%= a.last_name %></h4>
    <p><%= a.bio %></p>
    <%= link_to 'Learn More', a %>
  </div>
  <% end %>
</div>
<div class="jumbotron">
  <h1>ACTOR</h1>
  <p class="lead">ac·tor  (ăk′tər)</p>
  <p><%= link_to 'Movies', movies_path(), class:"btn btn-lg btn-success"%></p>
</div>

app/views/actors/show.html.erb
<div class="jumbotron">
  <h1><%= @actor.first_name %><%= @actor.last_name %></h1>
  <p class="lead"><%= @actor.bio %></p>
</div>
<div class="">
  <h3>Movies</h3>
</div>

<div class="row ">
  <% @movies.each do |m| %>
  <div class="col-md-4">
    <h4><%= m.title %></h4>
    <p><%= m.release_year %></p>
    <p><%= m.plot %></p>
    <%= link_to 'Learn more', m %>
  </div>
  <% end %>
</div>
<div class="jumbotron">
  <h1><%= @actor.first_name %><%= @actor.last_name %></h1>
  <%= link_to 'All Movies', movies_path(), class:"btn btn-success" %>
  <%= link_to 'All Actors', actors_path(), class:"btn btn-success" %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= yield(:title) %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">

<%= yield %>

  </div>
</body>
</html>

app/views/movies/index.html.erb
<div class="jumbotron">
        <h1>MOVIE</h1>
        <p class="lead">mov·ie  (mo͞o′vē)</p>
        <p><%= link_to 'Actors', actors_path(), class:"btn btn-lg btn-success"%></p>
</div>

      <div class="row ">
<% @movies.each do |m| %>
        <div class="col-md-6">
          <h4><%= m.title %></h4>
          <p><%= m.release_year %></p>
          <p><%= m.plot %></p>
          <%= link_to 'Learn More', m %>
        </div>
        <% end %>
      </div>

      <div class="jumbotron">
              <h1>MOVIE</h1>
              <p class="lead">mov·ie  (mo͞o′vē)</p>
              <p><%= link_to 'Actors', actors_path(), class:"btn btn-lg btn-success"%></p>
      </div>

app/views/movies/show.html.erb
<div class="jumbotron">
  <h1><%= @movie.title %></h1>
  <p class="lead"><%= @movie.release_year %></p>
  <p><%= @movie.plot %></p>
</div>
<div class="">
  <h3>CAST</h3>
</div>

<div class="row ">
  <% @actors.each do |a| %>

  <div class="col-md-6">
    <h4><%= a.first_name %><%= a.last_name %></h4>
    <p><%= a.bio %></p>
    <%= link_to 'Learn more', a %>
  </div>
  <% end %>
</div>
<div class="jumbotron">
  <%= simple_form_for([@movie, @movie.movie_quotes.build],{class:'form-inline'}) do |f| %>
  <h3>What's your favorite quote from</h3>

      <h1> <%= @movie.title %></h1>
      <%= f.input :source, label: false, placeholder: 'source' %>

  <p><%= f.button :submit, 'Add your favorite movie quote', class:'btn btn-success' %></p>
      <%= f.input :quote, label: false, placeholder: 'quote' %>
  <%= link_to 'All Movies', movies_path(), class:"btn btn-success" %>
  <%= link_to 'All Actors', actors_path(), class:"btn btn-success" %>
</div>
<% end %>
<div class="row ">
  <% @movie.movie_quotes.each do |q| %>
  <div class="col-md-6">
    <h4><%= q.quote %></h4>
    <p>-<%= q.source %></p>
  </div>
  <% end %>
</div>

app/views/pages/home.html.erb
<div class="main">
  <div class="container">
    <h1>Hello my name is Emerson</h1>
    <p>I have a broken arm that is still healing.</p>
  </div>
</div>

app/views/users/new.html.erb
<h1>Signup!</h1>

<%= form_for :user, url: '/users' do |f| %>

  Name: <%= f.text_field :first_name %>
        <%= f.text_field :last_name %>
  Email: <%= f.text_field :email %>
  Password: <%= f.password_field :password %>
  Password Confirmation: <%= f.password_field :password_confirmation %>
  <%= f.submit "Submit" %>

<% end %>


<!-- <div class="container">


    <%= title "Signup" %>

  <h1>Sign Up</h1>
  <form role="form">
  <%= simple_form_for(@user) do |f| %>
      <div class="form-group">
        <label for="first_name">First Name</label>
        <%= f.input :first_name, label: false %>
      </div>
      <div class="form-group">
        <label for="last_name">Last Name</label>
        <%= f.input :last_name, label: false %>
      </div>
       <div class="form-group">
        <label for="email">Email</label>
        <%= f.input :email, label: false  %>
      </div>
      <div class="form-group">
        <label for="password">Password</label>
        <%= f.input :password, label: false %>
      </div>
      <%= f.submit class:"btn btn-primary" %>
    <% end %>
    </form>

    <% if @user.errors.any? %>
    <ul class="Signup_Errors">
      <% for message_error in @user.errors.full_messages %>
      <li>*<%= message_error %></li>
    </ul>
    <% end %>
  </div>
  <% end %>
</div> -->